import { IAdvertListItem } from "./types/main";

export default [
    {
        id: 0,
        images: [
            'https://s00.yaplakal.com/pics/pics_original/4/0/7/17139704.jpg',
            'https://avatars.mds.yandex.net/i?id=74d0f660897f4dad66d70c94c63cee6f05169434-5467951-images-thumbs&n=13',
            'https://a.d-cd.net/474ff29s-1920.jpg',
            'https://hdpic.club/uploads/posts/2022-08/1660553027_41-hdpic-club-p-samii-ogromnii-tanker-49.jpg',
            'https://i07.fotocdn.net/s210/65575b78da75f122/public_pin_l/2660552460.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 1,
        images: [
            'http://u.kanobu.ru/editor/images/90/90d60810-9164-4606-8ecb-0d416de057d9.webp',
            'https://avatars.dzeninfra.ru/get-zen_doc/1576786/pub_62dd78ff0112073c7a35e0f1_62dd792594e04162bc9e2647/scale_1200',
            'https://i.redd.it/t9frlb8loec91.png',
            'https://www.kinonews.ru/insimgs/2017/shotimg/shotimg72090_1.jpg',
            'https://i.imgur.com/JTqS71V.jpg'
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 2,
        images: [
            'https://i.ytimg.com/vi/aQQkv5S6iEI/maxresdefault.jpg',
            'https://i.pinimg.com/originals/b5/97/42/b59742cefa4c5f3c1447c4a8a439035d.jpg',
            'https://studioprovans.ru/wp-content/uploads/9/2/a/92adf9ee5a4e6147556277943056ece6.jpeg',
            'https://www.wowcharter.ru/images/2.jpg',
            'https://screenmusings.org/movie/blu-ray/The-Wolf-of-Wall-Street/images/The-Wolf-of-Wall-Street-0784.jpg'
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 3,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 4,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 5,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 6,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 7,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 8,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
    {
        id: 9,
        images: [
            'https://i.ytimg.com/vi/jFSIKMUU4rY/maxresdefault.jpg',
            'https://i.imgur.com/XwA1soyh.jpg',
            'https://s00.yaplakal.com/pics/pics_original/1/0/9/15278901.jpg',
        ],
        title: 'Название Корабля',
        price: 100000,
        tags: [ 'тип', 'назначение', 'класс', 'мощность', 'флаг'],
        phone: '8-800-535-35-35',
        addres: 'Геленджик',
        isFavorite: false,
    },
] as IAdvertListItem[];